development:
  adapter: postgresql
  encoding: unicode
  database: rspec-device
  pool: 5
  username: postgres
  password: root
test:
  adapter: postgresql
  encoding: unicode
  database: rspec-device
  pool: 5
  username: postgres
  password: root
